foreground              #FFFFFF
background              #02040B
selection_foreground    #02040B
selection_background    #FFFFFF
cursor                  #F7FA0B 
cursor_text_color       #121215

active_tab_foreground     #02040B
active_tab_background     #D6B6B1
inactive_tab_foreground   #D6B6B1
inactive_tab_background   #02040B

# black
color0      #283151
color8      #57638E

# red
color1      #FEFFCC
color9      #EEEFAA

# green
color2      #CCF3FF
color10     #AADFEF

# yellow
color3      #FFD2CC
color11     #EFB3AA

# blue
color4      #99AAE5
color12     #99AAE5

# magenta
color5      #99D3E5
color13     #99D3E5

# cyan
color6      #E5A499
color14     #E5A499

# white
color7      #FEFFCC
color15     #EEEFAA
